### ISSUE TITLE
Card organization

### ISSUE THREAD

**Issue by cnell-usgs** [DOI-USGS/vizlab-home#5]
Current directions for card organization:
- Sections: Need partitioning of long-form vizzies, river conditions, hurricanes, and smaller one-off pieces that are shared on twitter. The exact groupings are less clear but we agree it should only be a few sections.
- Sorting: Within sections we want some ability to sort or filter based on tags assigned to each viz, like by IWS basin name, data type, release date, etc

Considerations
- Initial card sort by release date? I think this is ideal but then raises the question of what is featured on the main banner, as likely the banner and the first card showing would be the same
- River conditions, GW conditions, and hurricanes should direct to most recent release to reflect current events. 
- Using the accordion to show all river conditions when open will fill up the page very quickly and other vizzies may get lost. Think about how to feature most recent, make all available, and keep page easy to browse through.

**Comment by ceenell** [comment]
Current horizontal org within accordions:
- interactives 
- chart gallery
- events
within each accordion cards are organized by release date

- [ ] add option to reverse release date ordering

**Comment by cnell-usgs** [comment]
Accomplished in https://github.com/DOI-USGS/vizlab-home/releases/tag/v0.1.0
